// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNJGg2wwE17ohi3W_C0r7LYR2M6M7bdM4',
    appId: '1:593883469296:web:228da2060c5e674174b935',
    messagingSenderId: '593883469296',
    projectId: 'agrivoltaics-flutter-firebase',
    authDomain: 'agrivoltaics-flutter-firebase.firebaseapp.com',
    storageBucket: 'agrivoltaics-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgKu71k_qgSI9uswbkC2MjE1aiZHojqm0',
    appId: '1:593883469296:android:97e68bf71f2bce0c74b935',
    messagingSenderId: '593883469296',
    projectId: 'agrivoltaics-flutter-firebase',
    storageBucket: 'agrivoltaics-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcfblAeil6H0BMX_Zg7C2MnBlCORFsRo',
    appId: '1:593883469296:ios:62d6f701c81b99ea74b935',
    messagingSenderId: '593883469296',
    projectId: 'agrivoltaics-flutter-firebase',
    storageBucket: 'agrivoltaics-flutter-firebase.appspot.com',
    iosClientId: '593883469296-2ehkjtj2bgj1asn4e8kqj05mphq85398.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrivoltaicsFlutterApp',
  );
}
